project:
  type: website
  resources:
    - "/art/"


#  reference-location: margin
#  citation-location: margin

website:
  title: "CODAP for Australians"
  page-navigation: true

  sidebar:
    collapse-level : 1
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Introduction
      - href: 050-basics.qmd
        text: CODAP basics
      - href: 100-modelling.qmd
        text: Modelling
      - href: 210-stats.qmd
        text: Statistics • EDA
      - href: 220-stats-inference1.qmd
        text: Statistics • Inference
      - href: 230-stats-pulse.qmd
        text: Statistics • Pulse
      - href: 300-probability.qmd
        text: Probability
      - chapters : 
          - href: 310-prob-dice-30-1200.qmd
            text: Probability • dice
          - href: 320-two-coins-1000.qmd
            text: Probability • two coins
          - href: 330-ten-coins.qmd
            text: Probability • ten coins
      - href: 400-computational-thinking.qmd
        text: Computational thinking
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
